import { ContentCategory } from '@/types/editorial';

// Seed de categorías predefinidas con 8 temas cada una (64 temas totales)
export const defaultCategories: Omit<ContentCategory, 'id' | '_id' | 'createdAt' | 'updatedAt' | 'createdBy'>[] = [
  {
    slug: 'ventas',
    label: 'Ventas',
    icon: 'TrendingUp',
    isDefault: true,
    topics: [
      'Cómo cerrar más ventas en frío',
      '5 objeciones comunes y cómo manejarlas',
      'Scripts de seguimiento que sí funcionan',
      'Cómo calcular tu costo de adquisición de clientes',
      'Técnicas de upselling para PyMEs',
      'Cómo armar un pitch de 30 segundos',
      'Errores que alejan a tus prospectos',
      'Cómo pedir referidos sin ser incómodo',
    ],
  },
  {
    slug: 'finanzas',
    label: 'Finanzas',
    icon: 'Wallet',
    isDefault: true,
    topics: [
      'Cómo leer un estado de resultados',
      'Flujo de efectivo: la métrica que salva negocios',
      'Cuándo y cómo subir precios',
      'Cómo calcular tu punto de equilibrio',
      'Separar finanzas personales y del negocio',
      'Indicadores financieros que debes revisar cada mes',
      'Cómo prepararte para una auditoría del SAT',
      'Financiamiento para PyMEs: opciones reales',
    ],
  },
  {
    slug: 'operaciones',
    label: 'Operaciones',
    icon: 'Settings',
    isDefault: true,
    topics: [
      'Cómo documentar procesos sin morir en el intento',
      'Control de inventario para no expertos',
      'Métricas de productividad que sí importan',
      'Cómo delegar efectivamente',
      'Checklist para abrir/cerrar tu negocio cada día',
      'Cómo manejar proveedores difíciles',
      'Reducir costos sin afectar calidad',
      'Automatizaciones simples que ahorran horas',
    ],
  },
  {
    slug: 'legal-fiscal',
    label: 'Legal y Fiscal',
    icon: 'FileText',
    isDefault: true,
    topics: [
      'Qué es el CFDI 4.0 y cómo te afecta',
      'Obligaciones fiscales básicas de una PyME',
      'Cómo registrar tu marca en el IMPI',
      'Contratos que todo negocio debe tener',
      'Qué hacer si recibes una carta del SAT',
      'REPSE: qué es y quién debe registrarse',
      'Diferencias entre persona física y moral',
      'Cómo facturar correctamente',
    ],
  },
  {
    slug: 'rrhh',
    label: 'Recursos Humanos',
    icon: 'Users',
    isDefault: true,
    topics: [
      'Cómo reducir rotación de personal',
      'Onboarding efectivo en 5 pasos',
      'Cómo dar feedback difícil',
      'Estructura de compensación para PyMEs',
      'Obligaciones patronales con el IMSS',
      'Cómo hacer entrevistas que sí funcionen',
      'Cultura organizacional con poco presupuesto',
      'Cómo manejar conflictos entre empleados',
    ],
  },
  {
    slug: 'liderazgo',
    label: 'Liderazgo',
    icon: 'Target',
    isDefault: true,
    topics: [
      'Cómo llevar un consejo de administración',
      'Reuniones efectivas: menos tiempo, más resultados',
      'Cómo tomar decisiones difíciles',
      'El rol del fundador vs el rol del director',
      'Cómo comunicar malas noticias al equipo',
      'Planeación estratégica simplificada',
      'Cómo manejar el estrés de ser empresario',
      'Mentoría: cómo encontrar y aprovechar un mentor',
    ],
  },
  {
    slug: 'marketing',
    label: 'Marketing',
    icon: 'Megaphone',
    isDefault: true,
    topics: [
      'Marketing digital con $5,000 pesos al mes',
      'Cómo crear contenido sin ser experto',
      'Google My Business: guía completa',
      'Redes sociales: cuál elegir para tu negocio',
      'Cómo pedir reseñas a tus clientes',
      'Email marketing para principiantes',
      'Cómo diferenciarte de la competencia',
      'Errores comunes en publicidad de PyMEs',
    ],
  },
  {
    slug: 'tecnologia',
    label: 'Tecnología',
    icon: 'Laptop',
    isDefault: true,
    topics: [
      'Herramientas gratuitas para digitalizar tu negocio',
      'Cómo elegir un sistema de punto de venta',
      'Ciberseguridad básica para PyMEs',
      'CRM: qué es y por qué lo necesitas',
      'Automatizar WhatsApp Business',
      'Cómo evaluar si necesitas una app',
      'Respaldos: protege la información de tu negocio',
      'Inteligencia artificial práctica para PyMEs',
    ],
  },
];
